//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangmentUn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectLecture
    {
        public int Id { get; set; }
        public int SubjectId { get; set; }
        public string Tittle { get; set; }
        public string Content { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
